name:  15 - Working with Matrices
run-name: Matrices rock!
on: workflow_dispatch
jobs:
  backwards-compatability:
    name: ${{matrix.os}} - ${{matrix.node}}
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: true
      matrix:
        node: ['18.x', '20.x', '21.x']
        os:
          - ubuntu-latest
          - windows-latest
        include: 
           - os: ubuntu-latest
             node: '1ddd.x'
    steps:
      - name: Set-up node
        uses: actions/setup-node@v4
        with:
          node-version: ${{matrix.node}}
      - name: Perform some tests
        run: echo "Running test on  OS ${{matrix.os}} and Node version ${{matrix.node}}"
