name: 16 - Working with Matrices
run-name: Matrices rock again!!!
on: workflow_dispatch
jobs:
  include-example:
    name: ${{matrix.color}} - ${{matrix.shape}} - ${{matrix.size}} -  ${{matrix.tag || ''}}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        color: ['red', 'green']
        shape: ['circle', 'square']
        size: ['small', 'large']
        include:
          - color: red
            tag: cookie 
            
          - color: red
            shape: triangle
            size: small
          - color: red
            shape: triangle
            size: large 

        
    steps:
      - name: Dummy step
        run: echo ${{matrix.color}} - ${{matrix.shape}} - ${{matrix.size}}
